version: '3'
services:
  dynfiapp:
    container_name: dynfiapp
    restart: unless-stopped
    hostname: dynfiapp
    image: gfa/dynfi:23.2.2
    build:
      context: ./
      dockerfile: Dockerfile_Java
      args:
        DYNFI_VERSION: "23.2.2"
      
    volumes:
      - ./conf:/data/conf
    links:
      - dynfidb:dynfidb
    ports:
      - '9090:9090'

  dynfidb:
    container_name: dynfidb
    restart: unless-stopped
    hostname: dynfidb
    build:
      context: ./
      dockerfile: Dockerfile_mongo
    volumes:
      - mongo-db:/data/db

volumes:
  mongo-db:
    driver: local
