FROM alpine:3.11.2


RUN \
  echo 'http://dl-cdn.alpinelinux.org/alpine/v3.6/main' >> /etc/apk/repositories && \
  echo 'http://dl-cdn.alpinelinux.org/alpine/v3.6/community' >> /etc/apk/repositories && \
  apk update

# install Mongo
RUN \
  apk add mongodb=3.4.4-r0
  
# Create dir Mongo
RUN mkdir -p /data/db
RUN chown mongodb:mongodb /data/db


# Define mountable directories.
VOLUME ["/data/db"]

CMD [ "mongod" ] 
