FROM alpine:latest

ARG DYNFI_VERSION

RUN echo 'http://dl-cdn.alpinelinux.org/alpine/v3.6/main' >> /etc/apk/repositories
RUN echo 'http://dl-cdn.alpinelinux.org/alpine/v3.6/community' >> /etc/apk/repositories

RUN apk update

# install bash
RUN apk --no-cache --update add openjdk11 
RUN apk add --no-cache bash
RUN apk add --no-cache curl

# Create DIR config
RUN mkdir -p /data/conf
RUN mkdir -p /data/app

WORKDIR /data/app

# Download Dynfi binaries
RUN curl -o /data/app/dynfi.jar https://dynfi.com/files/dynfi/dynfi-$DYNFI_VERSION-all.jar

# Define mountable directories.
VOLUME ["/data/db"]
VOLUME ["/data/conf"]

# CGO has to be disabled for alpine

CMD [ "java", "-jar", "/data/app/dynfi.jar", "--config",  "/data/conf/custom.dynfi.conf" ]
